spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  mongodb:
#    database: ${DATABASE}
#    port: ${DB_PORT}
#    host: ${DB_HOST}

logging:
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
  level:
    root: INFO
    com:
      ps:
        backend: DEBUG
  file:
    name: ../logs/${spring.application.name}.log

SMTP_FROM: ${SMTP_FROM}
server:
  port: ${APPLICATION_PORT}
  servlet:
    context-path: /api

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: Microservice
    version: 1.0.0
